baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-theme-tailwindcss-starter"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpored =false

[build]
  writeStats = true
